// ---------------------------------------------------------------------------
// <copyright file="ComponentConfig.cs" company="eidng8">
//      GPLv3
// </copyright>
// <summary>
// 
// </summary>
// ---------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine;


namespace eidng8.SpaceFlight.Configurable.Ship
{
    public abstract class ComponentConfig : Configurable, IConfigurable
    {
        /// <summary>
        /// Positive value denotes how much power the component generates;
        /// negative value denotes constant power consumption of the component.
        /// For capacitors, this is the recharge rate.
        /// The amount of power generated by power generators, subtracted by
        /// total power consumption of all installed components, is charged to
        /// capacitors. All excess power are wasted if the excess power
        /// generated is more than the capacitors' recharge rate.
        /// </summary>
        [Header("Ship Component Attributes"),
         Tooltip(
             "Positive value denotes how much power the component generates; "
             + "negative value denotes constant power consumption of the component. "
             + "For capacitors, this is the recharge rate. "
             + "The amount of power generated by power generators, subtracted by "
             + "total power consumption of all installed components, is charged to "
             + "capacitors. All excess power are wasted if the excess power "
             + "generated is more than the capacitors' recharge rate."
         )]
        public float power;

        /// <summary>
        /// Positive value denotes how much space the component provides;
        /// negative value denotes how much space the component occupies.
        /// </summary>
        [Tooltip(
            "Positive value denotes how much space the component provides; "
            + "negative value denotes how much space the component occupies."
        )]
        public float size;

        /// <inheritdoc />
        public override Dictionary<string, float> Dict() {
            Dictionary<string, float> dict = base.Dict();
            dict["size"] = this.size;
            dict["power"] = this.power;
            return dict;
        }
    }
}
