@startuml
!include ../../styles.puml


start

-> ShipConfig;
: ShipFactory.Make()|
-> ship;

partition Ship {
    fork
        -> HullConfig;
        : HullFactory.Make()|
        -> hull:IHull;
        : ship.Fit()|
    fork again
        -> ThrusterConfig;
        : ThrusterFactory.Make()|
        -> thruster;
        fork
            -> ship.RigidBody;
            : thruster.MountTo()|
        fork again
            -> thruster;
            : NavigatorFactory.Make()|
            -> thruster:IThruster;
            : Navigator.Man()|
        end fork
    fork again
        -> components;
        repeat
        -> ComponentConfig;
        : ComponentFactory.Make()|
        -> component:IComponent;
        : ship.Mount()|
        repeat while (more component?) is (yes)
    end fork
}

-> ship;
end
@enduml
