@startuml

set namespaceSeparator .


interface INavigator {
    {readonly} HasTarget : bool
    Target : Transform
    + Man(IMovableObject, RigidBody) : void
    + FixedUpdate() : void
}

abstract class Navigator {
}

Navigator --|> INavigator


@enduml