@startuml
!include ../../styles.puml

set namespaceSeparator .


interface INavigator {
    {readonly} HasTarget : bool
    Target : Transform
    Configure(INavigatorConfig) : void
    Man(IThruster) : void
    ..Unity..
    FixedUpdate() : void
}

abstract class Navigator {
}

Navigator --|> INavigator
Navigator --> IThruster


@enduml