@startuml
!include ../../SpaceObject.puml

set namespaceSeparator .


class Ship {
    + {readonly} armor : float
    + {readonly} shield : float
    + {readonly} power : float
    + {readonly} energy : float
    + {readonly} capacitor : float
    
    + Use(int) : void
    ..Unity..
    # FixedUpdate() : void
}

Ship --|> SpaceObject
Ship --|> IMovableObject

Ship "1..*" *-- ComponentConfig

INavigator --o "1" Ship


@enduml