@startuml
!include ../../SpaceObject.puml
!include Components.puml

set namespaceSeparator .


class Ship {
    + {readonly} Armor : float
    + {readonly} MaxArmor : float
    + {readonly} Capacitor : float
    + {readonly} Energy : float
    + {readonly} Mass : float
    + {readonly} MaxForward : float
    + {readonly} MaxPan : float
    + {readonly} MaxReverse : float
    + {readonly} MaxTorque : float
    + {readonly} Power : float
    + {readonly} RechargeRate : float
    + {readonly} MaxShield : float
    + {readonly} Shield : float
    + {readonly} Speed : float
    + {readonly} Velocity : Vector3
    
    + Use(int) : void
    + Man(INavigator) : void
    ..Unity..
    # FixedUpdate() : void
}

Ship --|> SpaceObject
Ship --|> IMovableObject

Ship "1..*" *-- ComponentConfig

INavigator --o "1" Ship


@enduml