﻿@startuml
!include ../../colors.puml

set namespaceSeparator .

interface IThruster {
    {readonly} Speed : float
    {readonly} Velocity : Vector3
    {readonly} Acceleration : float
    Configure(IThrusterConfig) : void
    MountTo(RigidBody) : void
    GenerateThrust(Vector3) : void
    GenerateTorque(Vector3) : void
}


abstract class Thruster {
}

Thruster --|> IThruster


@enduml